window.TRACKER_DATA = {
  "lastUpdated": "2026-10-07T16:40:00-05:00",
  "jobs": [
    {
      "id": "aclu-cli-2027",
      "title": "Summer 2027 Criminal Law & Immigration Project Internship",
      "organization": "ACLU of Northern California",
      "category": "Justice & policing",
      "arrangement": "Hybrid / in person",
      "location": "San Francisco, Sacramento, or Fresno, CA",
      "pay": "Institutional funding encouraged; ACLU funding may be available",
      "deadline": "Open until filled",
      "eligibility": "Strong match",
      "fit": 99,
      "why": "Direct match for criminal justice, police accountability, prosecutorial accountability, decarceration, policy research, and advocacy.",
      "details": "Full-time for 10–12 weeks. The posting explicitly accepts graduate students in criminal justice, public policy, or related fields.",
      "url": "https://www.aclunorcal.org/jobs/summer-2027-criminal-law-immigration-project-internship/",
      "source": "ACLU NorCal",
      "future": false
    },
    {
      "id": "aclu-dst-2027",
      "title": "Summer 2027 Democracy, Speech & Technology Internship",
      "organization": "ACLU of Northern California",
      "category": "Surveillance, tech & civil liberties",
      "arrangement": "Hybrid / in person",
      "location": "San Francisco, Sacramento, or Fresno, CA",
      "pay": "Institutional funding encouraged; ACLU funding may be available",
      "deadline": "Open until filled",
      "eligibility": "Likely match",
      "fit": 97,
      "why": "Excellent fit for privacy, surveillance, digital civil liberties, technology policy, open government, research, and advocacy.",
      "details": "Full-time for 10–12 weeks. Open to graduate students in listed or related fields; confirm that criminology/criminal justice qualifies as a related field.",
      "url": "https://www.aclunorcal.org/jobs/summer-2027-democracy-speech-technology-internship/",
      "source": "ACLU NorCal",
      "future": false
    },
    {
      "id": "iacp-2027",
      "title": "Summer 2027 Internship Program",
      "organization": "International Association of Chiefs of Police (IACP)",
      "category": "Justice & policing",
      "arrangement": "In person",
      "location": "Alexandria, VA",
      "pay": "$15/hour",
      "deadline": "Not stated",
      "eligibility": "Strong match",
      "fit": 96,
      "why": "Direct policing exposure with opportunities that can span research, programs, policy, communications, and criminal-justice practice.",
      "details": "Summer 2027 term runs May 18–August 6. Program terms are 10–12 weeks with flexible schedules up to 40 hours/week.",
      "url": "https://www.theiacp.org/iacp-internship-program",
      "source": "IACP",
      "future": false
    },
    {
      "id": "cai-data-2027",
      "title": "Data Analyst Intern",
      "organization": "CAI",
      "category": "Research & data",
      "arrangement": "Remote",
      "location": "United States",
      "pay": "$20/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 93,
      "why": "Strong remote methods-building option for applied quantitative analysis, administrative data, visualization, and program evaluation.",
      "details": "Current listing is remote and full-time. Verify Summer 2027 timing and academic prerequisites in the application.",
      "url": "https://click.appcast.io/t/d_IXIb0tEucKhB6eExkN5snGrbmWcimn9GgT4beDHMDPt_UDR7n5hQM6Y2Rd-NhTq3Nfs3870u16FCBL1Bx9Gg==?sar_id=2alpiu5p&jpos=0",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "cai-program-2027",
      "title": "Program Analyst Intern",
      "organization": "CAI",
      "category": "Policy & program analysis",
      "arrangement": "Remote",
      "location": "United States",
      "pay": "$17/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 91,
      "why": "Remote program-analysis experience that transfers well to public-sector evaluation, policy analysis, and applied research.",
      "details": "Current listing identifies remote worksite flexibility and full-time employment.",
      "url": "https://click.appcast.io/t/K2XczRlpYduNF2p9Df2vBzkPFgsIq4z3fp5xXdcFILXm4SuXoZYDkbugtafFEqN5K32MxoaJRYlVG-FOHAjV9A==?sar_id=2alpitzb&jpos=2",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "landolakes-govrel-2027",
      "title": "Government Relations Intern",
      "organization": "Land O'Lakes",
      "category": "Government & policy",
      "arrangement": "Virtual + Washington, DC",
      "location": "Virtual / Washington, DC",
      "pay": "$23/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 90,
      "why": "Substantive government-relations and policy experience with a substantial virtual component.",
      "details": "Runs January–July 2027, so it overlaps Summer 2027 rather than being a summer-only internship.",
      "url": "https://to.indeed.com/aabmndwcvxh6",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "nhelp-mission-2027",
      "title": "Mission Advancement Summer Intern",
      "organization": "National Health Law Program",
      "category": "Nonprofit & policy",
      "arrangement": "Remote",
      "location": "Remote",
      "pay": "$14,997–$15,000 for internship",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 88,
      "why": "Fully remote public-interest nonprofit experience with advocacy, policy, and organizational research value.",
      "details": "The current posting specifically identifies Summer 2027 and states that the internship is fully remote.",
      "url": "https://to.indeed.com/aadrfhsrdxqs",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "conagra-analytics-2027",
      "title": "Analytics Internship — Summer 2027",
      "organization": "Conagra Brands",
      "category": "Research & data",
      "arrangement": "In person / verify",
      "location": "Omaha, NE",
      "pay": "$20–$28/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 87,
      "why": "Strong local quantitative option with transferable analytics experience if the best justice-specific roles require relocation.",
      "details": "Adjacent rather than justice-specific, but useful for applied analytics and staying in Omaha.",
      "url": "https://click.appcast.io/t/Mug-NnZF0iaYOxL7aWoJXQXPJ8dp0SCN465f4x_AIfBzZZMt3ooXwEYs7U3XtH_kHPCOGLMaxs4qmXw_q4IP4w==?sar_id=2alpiuo1&jpos=6",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "emblem-econ-2027",
      "title": "2027 Summer Healthcare Data Analytics — Healthcare Economics Intern",
      "organization": "EmblemHealth",
      "category": "Research & data",
      "arrangement": "Remote",
      "location": "Remote",
      "pay": "$30/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 86,
      "why": "Applied quantitative research in a policy-heavy regulated domain; useful for statistics, evaluation, and causal-thinking experience.",
      "details": "Summer 2027 remote internship. Subject matter is healthcare economics rather than criminal justice.",
      "url": "https://to.indeed.com/aa9vvk7mn6mr",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "amgen-grad-ds-2027",
      "title": "Grad Intern — Data Scientist — Technology, AI & Data (Summer 2027)",
      "organization": "Amgen",
      "category": "Research, data & AI",
      "arrangement": "Remote",
      "location": "United States — Remote",
      "pay": "$35.34–$41.20/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 84,
      "why": "Graduate-level remote data-science experience that could strengthen statistical modeling, AI, and large-data skills.",
      "details": "Adjacent rather than justice-specific. Confirm degree-field prerequisites before applying.",
      "url": "https://to.indeed.com/aaslgbwn7xmk",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "stryker-raqa-2027",
      "title": "Summer 2027 Internship — Post Market Regulatory Affairs",
      "organization": "Stryker",
      "category": "Regulation & compliance",
      "arrangement": "Virtual",
      "location": "Virtual / listed for Omaha, NE",
      "pay": "$35/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 82,
      "why": "Remote regulatory/compliance work is adjacent to interests in institutions, accountability, rules, and technology governance.",
      "details": "A useful backup if you want remote analytical or policy experience outside criminal justice.",
      "url": "https://www.ziprecruiter.com/job-redirect?match_token=Cp8BChZFWUMwMU4zczNOQkpjanhfLThUTm93EiQwMWExMTNiMC1lNjNmLTc0YzMtYWE0Yy05ZDdjZGQxYWY5N2YaW0FBRWdMZE1LN1FzSF9Sd0N2X3FPZ29TcGlaN1lkREtNckE0RW9EWjR5M1BSUDJZQ0RUalFsZkxQUTY3WE8tLVpwcDhrTFJqeUxtRXVtbm45TGJ2Zk9GdmFFT3Mg5a0FEAEY5a0F&server_redirect=true&tsid=100000600",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "nmpf-policy-2027",
      "title": "Paid Summer 2027 Internship",
      "organization": "National Milk Producers Federation",
      "category": "Government & policy",
      "arrangement": "In person",
      "location": "Arlington, VA / Washington, DC metro",
      "pay": "$18/hour",
      "deadline": "Not stated",
      "eligibility": "Check requirements",
      "fit": 76,
      "why": "Broader Washington policy exposure; a reasonable adjacent option if justice-specific opportunities are limited.",
      "details": "10–12 week summer internship focused on the intersection of industry and U.S. policy.",
      "url": "https://to.indeed.com/aatvqhk7p8ls",
      "source": "Current job listing",
      "future": false
    },
    {
      "id": "brennan-justice-legal-2027",
      "title": "Summer 2027 Justice Legal Internship",
      "organization": "Brennan Center for Justice",
      "category": "Future JD watchlist",
      "arrangement": "In person / verify",
      "location": "New York, NY",
      "pay": "See posting",
      "deadline": "See posting",
      "eligibility": "Law students only",
      "fit": 94,
      "why": "Excellent substantive fit for criminal-justice reform and policy, but it belongs on a future-JD list unless you are enrolled in law school.",
      "details": "Kept separate so law-student-only roles do not crowd out opportunities you can pursue as a criminology graduate student.",
      "url": "https://www.brennancenter.org/about/employment/current-openings",
      "source": "Brennan Center",
      "future": true
    },
    {
      "id": "middlesex-prosecutor-grad-2027",
      "title": "Graduate Internship Program — Summer 2027",
      "organization": "Middlesex County Prosecutor's Office",
      "category": "Justice & policing",
      "arrangement": "In person",
      "location": "New Brunswick, NJ",
      "pay": "$15.49/hour for paid slots; some unpaid slots",
      "deadline": "December 31, 2026",
      "eligibility": "Strong match",
      "fit": 99,
      "why": "One of the strongest direct matches: a graduate-level criminal-justice and law-enforcement internship supporting prosecution, research, and investigations, with preference for criminal justice or related graduate study.",
      "details": "Approximately 11 weeks from June through August 2027. Requires completion of the first graduate year and continued enrollment in an accredited graduate program.",
      "url": "https://host.careersingovernment.com/job/3056183/graduate-internship-program-middlesex-county-prosecutor-s-office-summer-2027/",
      "source": "Middlesex County / Careers in Government",
      "future": false
    },
    {
      "id": "ppg-buffalo-2027",
      "title": "Paid Summer 2027 Internship",
      "organization": "Partnership for the Public Good",
      "category": "Justice, policy & research",
      "arrangement": "Hybrid",
      "location": "Buffalo, NY",
      "pay": "$20/hour",
      "deadline": "Rolling",
      "eligibility": "Strong match",
      "fit": 98,
      "why": "Exceptional master's-level policy and research fit with direct work on criminal justice, civil rights, government, and community policy using qualitative and quantitative research.",
      "details": "Eight weeks from early June to late July 2027, 35 hours/week. The summer schedule is 3 days in person and 2 days remote, and the program is mainly geared toward master's and JD students.",
      "url": "https://ppgbuffalo.org/news-and-events/news/article:10-02-2026-12-00am-ppg-is-hiring-a-paid-intern-for-summer-2027-applications-open/",
      "source": "Partnership for the Public Good",
      "future": false
    },
    {
      "id": "progressive-data-2027",
      "title": "Data Analyst Internship — Summer 2027",
      "organization": "Progressive",
      "category": "Research & data",
      "arrangement": "Remote",
      "location": "United States — Remote",
      "pay": "$26.50/hour",
      "deadline": "Not stated",
      "eligibility": "Likely match",
      "fit": 92,
      "why": "Strong fully remote analytics option with large-data, statistical, and business-analysis work that would build transferable quantitative skills.",
      "details": "Runs May–August 2027. Applicants must be pursuing a bachelor's degree or higher in a quantitative field; work may involve pricing, actuarial analytics, or the Analyst Development Program and tools such as Python, R, SQL, Excel, Tableau, or SAS.",
      "url": "https://earlycareers.progressive.com/jobs/18156166-data-analyst-internship-summer-2027/",
      "source": "Progressive",
      "future": false
    },
    {
      "id": "veeam-data-2027",
      "title": "Data Analytics & Programs Intern — Summer 2027",
      "organization": "Veeam",
      "category": "Research & data",
      "arrangement": "Hybrid",
      "location": "Georgia, US",
      "pay": "$20–$25/hour",
      "deadline": "Not stated",
      "eligibility": "Likely match",
      "fit": 91,
      "why": "Graduate-eligible analytics role focused on turning operational and customer-feedback data into findings, dashboards, recommendations, and program materials.",
      "details": "10-week program from June through August 2027. Graduate students are eligible; preferred fields include statistics, data analytics, business administration, marketing, or a related field.",
      "url": "https://careers.veeam.com/job/georgia/data-analytics-and-programs-intern-summer-2027/22681/100489030400",
      "source": "Veeam",
      "future": false
    },
    {
      "id": "principal-data-2027",
      "title": "Data and Analytics Internship — Undergraduate and Graduate (Summer 2027)",
      "organization": "Principal Financial Group",
      "category": "Research & data",
      "arrangement": "Remote / hybrid / in person",
      "location": "Des Moines, IA; Charlotte, NC; Raleigh, NC",
      "pay": "$30–$32/hour for graduate interns",
      "deadline": "Posting may close based on applicant volume",
      "eligibility": "Strong match",
      "fit": 91,
      "why": "Graduate-level Summer 2027 analytics program with tracks in data analytics, data science, data consulting, data governance, and business intelligence, including interest in quantitative social-science methods.",
      "details": "Offers in-office, hybrid, and remote arrangements; remote eligibility generally applies when residing more than 30 miles from the listed offices. The program also provides a $4,000 internship stipend.",
      "url": "https://careers.principal.com/careers-home/jobs/52574",
      "source": "Principal Financial Group",
      "future": false
    },
    {
      "id": "npap-law-clerk-2027",
      "title": "Law Clerk — Summer 2027",
      "organization": "National Police Accountability Project",
      "category": "Future JD watchlist",
      "arrangement": "Likely remote / in-person options",
      "location": "United States",
      "pay": "$5,000 stipend",
      "deadline": "Until filled",
      "eligibility": "Law students only",
      "fit": 100,
      "why": "Near-perfect future JD fit: police accountability, civil-rights litigation, legislative strategy, policy research, and law-enforcement accountability.",
      "details": "Runs June 7–August 6, 2027. Open to 2L students; the position will likely be remote, with in-person options available.",
      "url": "https://nationalpoliceaccountability.org/careers/",
      "source": "National Police Accountability Project",
      "future": true
    },
    {
      "id": "aclu-spt-legal-2027",
      "title": "Summer 2027 Legal Intern — Speech, Privacy and Technology Project",
      "organization": "ACLU National",
      "category": "Future JD watchlist",
      "arrangement": "Remote / hybrid",
      "location": "New York City / Remote",
      "pay": "$24/hour stipend",
      "deadline": "Priority deadline October 18, 2026",
      "eligibility": "Law students only",
      "fit": 100,
      "why": "Exceptional future JD fit for surveillance, privacy, technology, civil liberties, big-data policy, and constitutional litigation.",
      "details": "Full-time for 10 consecutive weeks, starting May 24 or June 7. Applicants must be matriculated law students who have completed their first year before the internship begins, or be in an LLM program.",
      "url": "https://job-boards.greenhouse.io/acluinternships/jobs/8843280002",
      "source": "ACLU National",
      "future": true
    },
    {
      "id": "meijer-risk-intelligence-2027",
      "title": "Risk Intelligence Intern — Summer 2027",
      "organization": "Meijer",
      "category": "Justice, surveillance & data",
      "arrangement": "Hybrid",
      "location": "Grand Rapids, MI",
      "pay": "$12.50–$16.75/hour",
      "deadline": "Not stated",
      "eligibility": "Strong match",
      "fit": 99,
      "why": "Unusually direct overlap with criminal justice, surveillance technology, investigations, data analysis, and partnerships with law enforcement and prosecutors.",
      "details": "Full-time 11-week Summer 2027 internship. Work includes organized retail crime, fraud and internal investigations, asset-protection technology evaluation, surveillance-technology privacy/governance, and analytics using tools such as Python, R, or SQL. Progress toward a bachelor's or master's degree in an analytics-related field is accepted.",
      "url": "https://meijer.wd5.myworkdayjobs.com/en-US/Meijer/job/Grand-Rapids-MI/Risk-Intelligence-Intern--Summer-2027_R000700477",
      "source": "Meijer",
      "future": false
    },
    {
      "id": "centene-analytics-grad-2027",
      "title": "Analytics Summer 2027 Intern — Graduate",
      "organization": "Centene",
      "category": "Research & data",
      "arrangement": "Remote",
      "location": "Remote — Florida",
      "pay": "$21–$30/hour",
      "deadline": "Not stated",
      "eligibility": "Likely match",
      "fit": 94,
      "why": "Graduate-level remote analytics work spanning data science, advanced analytics, business intelligence, AI/ML, and reporting; strong methods-building experience for evaluation and policy research.",
      "details": "Full-time Summer 2027 graduate internship. Requires a completed bachelor's degree and current enrollment in a graduate program related to the hiring department; listed fields include data science, analytics, statistics, applied math, information systems, business analytics, biostatistics, public-health analytics, health informatics, or a related graduate field.",
      "url": "https://jobs.centene.com/us/en/jobs/1660479/analytics-summer-2027-intern-graduate/",
      "source": "Centene",
      "future": false
    },
    {
      "id": "humana-grad-analytics-2027",
      "title": "Graduate Analytics Internship — Summer 2027",
      "organization": "Humana",
      "category": "Research, data & policy",
      "arrangement": "Hybrid / in person",
      "location": "Louisville, KY; Arlington, VA; Chicago, IL; Ft. Lauderdale, FL; Nashville, TN; New York, NY",
      "pay": "See posting",
      "deadline": "Not stated",
      "eligibility": "Likely match",
      "fit": 91,
      "why": "Strong graduate-level quantitative option involving exploratory analysis, statistical modeling, reproducible methods, research, and policy-governance work.",
      "details": "12-week internship from May 24–August 13, 2027, generally 3–4 office days per week. Applicants must be current full-time graduate students in a quantitative or related field; projects can include analytics, research/data science, and policy governance.",
      "url": "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site/job/Louisville-KY/Graduate-Analytics-Internship---Summer-2027_R-429772",
      "source": "Humana",
      "future": false
    },
    {
      "id": "stop-comms-summer-2027",
      "title": "Social Media & Communications Internship — Summer 2027",
      "organization": "Surveillance Technology Oversight Project (S.T.O.P.)",
      "category": "Surveillance, privacy & civil liberties",
      "arrangement": "Remote",
      "location": "Remote / New York, NY",
      "pay": "Unpaid; outside funding or college credit",
      "deadline": "Not stated",
      "eligibility": "Strong match",
      "fit": 92,
      "why": "Direct substantive exposure to surveillance, privacy, civil rights, and technology policy at an organization focused specifically on government surveillance and accountability.",
      "details": "S.T.O.P. is accepting Spring and Summer 2027 interns. Undergraduate and graduate students or recent graduates may apply. The role emphasizes research, writing, breaking-news monitoring, communications, and civil-rights/privacy issues, and internships can operate 100% remotely.",
      "url": "https://www.stopspying.org/internships",
      "source": "S.T.O.P.",
      "future": false
    },
    {
      "id": "centene-health-admin-grad-2027",
      "title": "Healthcare Administration Summer 2027 Intern — Graduate",
      "organization": "Centene",
      "category": "Policy & program analysis",
      "arrangement": "Remote",
      "location": "Remote — Missouri",
      "pay": "$21–$30/hour",
      "deadline": "Not stated",
      "eligibility": "Likely match",
      "fit": 88,
      "why": "Remote graduate-level policy and program-analysis experience involving public health, health policy, quality improvement, strategy, operations, and performance measurement.",
      "details": "Summer 2027 graduate internship for students enrolled in a graduate program related to the hiring department. Projects can span public health, population health, health policy, quality improvement, care management, operations, strategy, and performance.",
      "url": "https://jobs.centene.com/us/en/jobs/1660478/healthcare-administration-summer-2027-intern-graduate/",
      "source": "Centene",
      "future": false
    },
    {
      "id": "aclu-clrp-legal-2027",
      "title": "Summer 2027 Legal Intern — Criminal Law Reform Project",
      "organization": "ACLU National",
      "category": "Future JD watchlist",
      "arrangement": "Hybrid",
      "location": "New York, NY / Washington, DC",
      "pay": "$24/hour stipend",
      "deadline": "See posting",
      "eligibility": "Law students only",
      "fit": 100,
      "why": "Near-perfect future JD fit for criminal-justice reform, policing, prosecution, incarceration, civil rights, litigation, and policy advocacy.",
      "details": "Full-time 35 hours/week for 10 consecutive weeks, beginning May 24 or June 7, 2027. Kept on the future-JD watchlist because it is a legal internship requiring law-school enrollment.",
      "url": "https://www.aclu.org/careers/summer-2027-legal-intern-criminal-law-reform-project",
      "source": "ACLU National",
      "future": true
    },
    {
      "id": "aclu-nsp-legal-2027",
      "title": "Summer 2027 Legal Intern — National Security Project",
      "organization": "ACLU National",
      "category": "Future JD watchlist",
      "arrangement": "Hybrid",
      "location": "New York, NY",
      "pay": "$24/hour stipend",
      "deadline": "Priority deadlines vary by class year",
      "eligibility": "Law students only",
      "fit": 99,
      "why": "Excellent future JD match for surveillance, state power, privacy, civil liberties, national security, constitutional litigation, and government accountability.",
      "details": "Full-time 35 hours/week for 10 consecutive weeks. Applicants must be law students with at least one year completed before the internship. Kept separate as a future-JD opportunity.",
      "url": "https://www.aclu.org/careers/summer-2027-legal-intern-national-security-project",
      "source": "ACLU National",
      "future": true
    }
  ],
  "lastSearched": "2026-10-07T16:40:00-05:00",
  "newSinceLastRefresh": 7,
  "newJobIds": [
    "meijer-risk-intelligence-2027",
    "centene-analytics-grad-2027",
    "humana-grad-analytics-2027",
    "stop-comms-summer-2027",
    "centene-health-admin-grad-2027",
    "aclu-clrp-legal-2027",
    "aclu-nsp-legal-2027"
  ]
};
